// window.dummyTradesmen = [
//   {
//     id: 1,
//     name: "John Doe",
//     specializations: ["Framing", "Drywall", "Tile", "Paint"],
//     location: "New York, NY",
//     attributes: {
//       "General Knowledge/Understanding": 80,
//       "Physical Strength": 85,
//       Reliability: 90,
//       Conscientiousness: 88,
//       Stamina: 82,
//       Safety: 95,
//       "Technical Knowledge": 87,
//       Heights: 75,
//       Experience: 89,
//       "Attitude/Social Abilities": 92,
//       "Customer Service": 91,
//       Math: 83,
//       Confidence: 88,
//       Initiative: 86,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 2,
//     name: "Jane Smith",
//     specializations: ["Electrical", "Plumbing", "HVAC"],
//     location: "Los Angeles, CA",
//     attributes: {
//       "General Knowledge/Understanding": 92,
//       "Physical Strength": 78,
//       Reliability: 95,
//       Conscientiousness: 90,
//       Stamina: 85,
//       Safety: 98,
//       "Technical Knowledge": 94,
//       Heights: 80,
//       Experience: 91,
//       "Attitude/Social Abilities": 88,
//       "Customer Service": 93,
//       Math: 90,
//       Confidence: 92,
//       Initiative: 89,
//       "Work Ethic": 96,
//     },
//   },
//   {
//     id: 3,
//     name: "Mike Johnson",
//     specializations: ["Carpentry", "Woodworking"],
//     location: "Chicago, IL",
//     attributes: {
//       "General Knowledge/Understanding": 88,
//       "Physical Strength": 92,
//       Reliability: 87,
//       Conscientiousness: 85,
//       Stamina: 90,
//       Safety: 93,
//       "Technical Knowledge": 89,
//       Heights: 82,
//       Experience: 94,
//       "Attitude/Social Abilities": 86,
//       "Customer Service": 88,
//       Math: 85,
//       Confidence: 91,
//       Initiative: 87,
//       "Work Ethic": 92,
//     },
//   },
//   {
//     id: 4,
//     name: "Emily Brown",
//     specializations: ["Masonry", "Concrete"],
//     location: "Houston, TX",
//     attributes: {
//       "General Knowledge/Understanding": 85,
//       "Physical Strength": 88,
//       Reliability: 92,
//       Conscientiousness: 89,
//       Stamina: 87,
//       Safety: 94,
//       "Technical Knowledge": 86,
//       Heights: 79,
//       Experience: 90,
//       "Attitude/Social Abilities": 93,
//       "Customer Service": 91,
//       Math: 87,
//       Confidence: 89,
//       Initiative: 88,
//       "Work Ethic": 95,
//     },
//   },
//   {
//     id: 5,
//     name: "David Lee",
//     specializations: ["Roofing", "Siding"],
//     location: "Phoenix, AZ",
//     attributes: {
//       "General Knowledge/Understanding": 87,
//       "Physical Strength": 90,
//       Reliability: 89,
//       Conscientiousness: 86,
//       Stamina: 93,
//       Safety: 96,
//       "Technical Knowledge": 88,
//       Heights: 95,
//       Experience: 92,
//       "Attitude/Social Abilities": 85,
//       "Customer Service": 87,
//       Math: 84,
//       Confidence: 90,
//       Initiative: 88,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 6,
//     name: "Sarah Wilson",
//     specializations: ["Landscaping", "Irrigation"],
//     location: "Philadelphia, PA",
//     attributes: {
//       "General Knowledge/Understanding": 89,
//       "Physical Strength": 84,
//       Reliability: 93,
//       Conscientiousness: 91,
//       Stamina: 88,
//       Safety: 92,
//       "Technical Knowledge": 90,
//       Heights: 81,
//       Experience: 87,
//       "Attitude/Social Abilities": 94,
//       "Customer Service": 95,
//       Math: 86,
//       Confidence: 89,
//       Initiative: 92,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 7,
//     name: "Tom Garcia",
//     specializations: ["Welding", "Metalwork"],
//     location: "San Antonio, TX",
//     attributes: {
//       "General Knowledge/Understanding": 91,
//       "Physical Strength": 93,
//       Reliability: 88,
//       Conscientiousness: 87,
//       Stamina: 92,
//       Safety: 97,
//       "Technical Knowledge": 95,
//       Heights: 84,
//       Experience: 93,
//       "Attitude/Social Abilities": 86,
//       "Customer Service": 85,
//       Math: 89,
//       Confidence: 93,
//       Initiative: 90,
//       "Work Ethic": 91,
//     },
//   },
//   {
//     id: 8,
//     name: "Lisa Martinez",
//     specializations: ["Interior Design", "Home Staging"],
//     location: "San Diego, CA",
//     attributes: {
//       "General Knowledge/Understanding": 93,
//       "Physical Strength": 79,
//       Reliability: 91,
//       Conscientiousness: 94,
//       Stamina: 83,
//       Safety: 90,
//       "Technical Knowledge": 92,
//       Heights: 78,
//       Experience: 88,
//       "Attitude/Social Abilities": 96,
//       "Customer Service": 97,
//       Math: 88,
//       Confidence: 94,
//       Initiative: 93,
//       "Work Ethic": 92,
//     },
//   },
//   {
//     id: 9,
//     name: "Chris Taylor",
//     specializations: ["Flooring", "Tile"],
//     location: "Dallas, TX",
//     attributes: {
//       "General Knowledge/Understanding": 86,
//       "Physical Strength": 89,
//       Reliability: 92,
//       Conscientiousness: 88,
//       Stamina: 91,
//       Safety: 93,
//       "Technical Knowledge": 87,
//       Heights: 80,
//       Experience: 90,
//       "Attitude/Social Abilities": 89,
//       "Customer Service": 92,
//       Math: 85,
//       Confidence: 88,
//       Initiative: 87,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 10,
//     name: "Amanda White",
//     specializations: ["Painting", "Wallpapering"],
//     location: "San Jose, CA",
//     attributes: {
//       "General Knowledge/Understanding": 88,
//       "Physical Strength": 82,
//       Reliability: 94,
//       Conscientiousness: 93,
//       Stamina: 86,
//       Safety: 91,
//       "Technical Knowledge": 89,
//       Heights: 83,
//       Experience: 91,
//       "Attitude/Social Abilities": 95,
//       "Customer Service": 96,
//       Math: 84,
//       Confidence: 90,
//       Initiative: 91,
//       "Work Ethic": 95,
//     },
//   },
//   {
//     id: 11,
//     name: "Robert Chen",
//     specializations: ["HVAC", "Refrigeration"],
//     location: "Jacksonville, FL",
//     attributes: {
//       "General Knowledge/Understanding": 94,
//       "Physical Strength": 86,
//       Reliability: 92,
//       Conscientiousness: 90,
//       Stamina: 88,
//       Safety: 95,
//       "Technical Knowledge": 96,
//       Heights: 85,
//       Experience: 93,
//       "Attitude/Social Abilities": 87,
//       "Customer Service": 89,
//       Math: 92,
//       Confidence: 91,
//       Initiative: 90,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 12,
//     name: "Emma Rodriguez",
//     specializations: ["Plumbing", "Gas Fitting"],
//     location: "Indianapolis, IN",
//     attributes: {
//       "General Knowledge/Understanding": 90,
//       "Physical Strength": 84,
//       Reliability: 93,
//       Conscientiousness: 91,
//       Stamina: 87,
//       Safety: 96,
//       "Technical Knowledge": 92,
//       Heights: 82,
//       Experience: 89,
//       "Attitude/Social Abilities": 94,
//       "Customer Service": 95,
//       Math: 88,
//       Confidence: 90,
//       Initiative: 91,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 13,
//     name: "Daniel Kim",
//     specializations: ["Electrical", "Solar Installation"],
//     location: "Columbus, OH",
//     attributes: {
//       "General Knowledge/Understanding": 93,
//       "Physical Strength": 85,
//       Reliability: 91,
//       Conscientiousness: 92,
//       Stamina: 86,
//       Safety: 97,
//       "Technical Knowledge": 95,
//       Heights: 88,
//       Experience: 90,
//       "Attitude/Social Abilities": 89,
//       "Customer Service": 92,
//       Math: 94,
//       Confidence: 93,
//       Initiative: 90,
//       "Work Ethic": 92,
//     },
//   },
//   {
//     id: 14,
//     name: "Olivia Patel",
//     specializations: ["Landscaping", "Hardscaping"],
//     location: "Austin, TX",
//     attributes: {
//       "General Knowledge/Understanding": 89,
//       "Physical Strength": 87,
//       Reliability: 94,
//       Conscientiousness: 93,
//       Stamina: 90,
//       Safety: 92,
//       "Technical Knowledge": 88,
//       Heights: 83,
//       Experience: 91,
//       "Attitude/Social Abilities": 95,
//       "Customer Service": 96,
//       Math: 86,
//       Confidence: 91,
//       Initiative: 93,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 15,
//     name: "James Wilson",
//     specializations: ["Carpentry", "Cabinet Making"],
//     location: "Memphis, TN",
//     attributes: {
//       "General Knowledge/Understanding": 91,
//       "Physical Strength": 89,
//       Reliability: 90,
//       Conscientiousness: 88,
//       Stamina: 92,
//       Safety: 94,
//       "Technical Knowledge": 93,
//       Heights: 86,
//       Experience: 95,
//       "Attitude/Social Abilities": 87,
//       "Customer Service": 89,
//       Math: 90,
//       Confidence: 92,
//       Initiative: 91,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 16,
//     name: "Sophia Nguyen",
//     specializations: ["Interior Design", "Color Consultation"],
//     location: "Baltimore, MD",
//     attributes: {
//       "General Knowledge/Understanding": 95,
//       "Physical Strength": 80,
//       Reliability: 93,
//       Conscientiousness: 96,
//       Stamina: 84,
//       Safety: 91,
//       "Technical Knowledge": 94,
//       Heights: 82,
//       Experience: 92,
//       "Attitude/Social Abilities": 97,
//       "Customer Service": 98,
//       Math: 89,
//       Confidence: 95,
//       Initiative: 94,
//       "Work Ethic": 96,
//     },
//   },
//   {
//     id: 17,
//     name: "Ethan Brown",
//     specializations: ["Welding", "Metal Fabrication"],
//     location: "Nashville, TN",
//     attributes: {
//       "General Knowledge/Understanding": 92,
//       "Physical Strength": 94,
//       Reliability: 89,
//       Conscientiousness: 88,
//       Stamina: 93,
//       Safety: 96,
//       "Technical Knowledge": 95,
//       Heights: 87,
//       Experience: 91,
//       "Attitude/Social Abilities": 86,
//       "Customer Service": 85,
//       Math: 90,
//       Confidence: 93,
//       Initiative: 91,
//       "Work Ethic": 92,
//     },
//   },
//   {
//     id: 18,
//     name: "Ava Thompson",
//     specializations: ["Masonry", "Stone Work"],
//     location: "Fort Worth, TX",
//     attributes: {
//       "General Knowledge/Understanding": 88,
//       "Physical Strength": 91,
//       Reliability: 93,
//       Conscientiousness: 90,
//       Stamina: 92,
//       Safety: 95,
//       "Technical Knowledge": 89,
//       Heights: 85,
//       Experience: 94,
//       "Attitude/Social Abilities": 87,
//       "Customer Service": 88,
//       Math: 86,
//       Confidence: 90,
//       Initiative: 89,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 19,
//     name: "Noah Garcia",
//     specializations: ["Roofing", "Gutter Installation"],
//     location: "Charlotte, NC",
//     attributes: {
//       "General Knowledge/Understanding": 89,
//       "Physical Strength": 92,
//       Reliability: 90,
//       Conscientiousness: 87,
//       Stamina: 94,
//       Safety: 96,
//       "Technical Knowledge": 88,
//       Heights: 97,
//       Experience: 91,
//       "Attitude/Social Abilities": 86,
//       "Customer Service": 88,
//       Math: 85,
//       Confidence: 91,
//       Initiative: 89,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 20,
//     name: "Isabella Martinez",
//     specializations: ["Painting", "Faux Finishing"],
//     location: "Detroit, MI",
//     attributes: {
//       "General Knowledge/Understanding": 90,
//       "Physical Strength": 84,
//       Reliability: 93,
//       Conscientiousness: 92,
//       Stamina: 87,
//       Safety: 91,
//       "Technical Knowledge": 89,
//       Heights: 85,
//       Experience: 90,
//       "Attitude/Social Abilities": 94,
//       "Customer Service": 95,
//       Math: 86,
//       Confidence: 91,
//       Initiative: 92,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 21,
//     name: "Liam Johnson",
//     specializations: ["Framing", "Structural Carpentry"],
//     location: "El Paso, TX",
//     attributes: {
//       "General Knowledge/Understanding": 91,
//       "Physical Strength": 93,
//       Reliability: 89,
//       Conscientiousness: 88,
//       Stamina: 92,
//       Safety: 94,
//       "Technical Knowledge": 90,
//       Heights: 87,
//       Experience: 92,
//       "Attitude/Social Abilities": 86,
//       "Customer Service": 87,
//       Math: 89,
//       Confidence: 91,
//       Initiative: 88,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 22,
//     name: "Mia Davis",
//     specializations: ["Electrical", "Smart Home Installation"],
//     location: "Seattle, WA",
//     attributes: {
//       "General Knowledge/Understanding": 94,
//       "Physical Strength": 82,
//       Reliability: 92,
//       Conscientiousness: 93,
//       Stamina: 85,
//       Safety: 97,
//       "Technical Knowledge": 96,
//       Heights: 84,
//       Experience: 91,
//       "Attitude/Social Abilities": 90,
//       "Customer Service": 93,
//       Math: 95,
//       Confidence: 92,
//       Initiative: 91,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 23,
//     name: "Benjamin Lee",
//     specializations: ["Plumbing", "Water Treatment"],
//     location: "Denver, CO",
//     attributes: {
//       "General Knowledge/Understanding": 92,
//       "Physical Strength": 88,
//       Reliability: 94,
//       Conscientiousness: 91,
//       Stamina: 89,
//       Safety: 96,
//       "Technical Knowledge": 93,
//       Heights: 83,
//       Experience: 92,
//       "Attitude/Social Abilities": 90,
//       "Customer Service": 92,
//       Math: 91,
//       Confidence: 90,
//       Initiative: 89,
//       "Work Ethic": 95,
//     },
//   },
//   {
//     id: 24,
//     name: "Charlotte Wilson",
//     specializations: ["Flooring", "Carpet Installation"],
//     location: "Washington, DC",
//     attributes: {
//       "General Knowledge/Understanding": 88,
//       "Physical Strength": 86,
//       Reliability: 93,
//       Conscientiousness: 90,
//       Stamina: 89,
//       Safety: 92,
//       "Technical Knowledge": 87,
//       Heights: 81,
//       Experience: 91,
//       "Attitude/Social Abilities": 94,
//       "Customer Service": 95,
//       Math: 85,
//       Confidence: 89,
//       Initiative: 90,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 25,
//     name: "William Taylor",
//     specializations: ["HVAC", "Energy Efficiency"],
//     location: "Boston, MA",
//     attributes: {
//       "General Knowledge/Understanding": 93,
//       "Physical Strength": 87,
//       Reliability: 91,
//       Conscientiousness: 90,
//       Stamina: 88,
//       Safety: 95,
//       "Technical Knowledge": 94,
//       Heights: 85,
//       Experience: 90,
//       "Attitude/Social Abilities": 89,
//       "Customer Service": 92,
//       Math: 91,
//       Confidence: 90,
//       Initiative: 88,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 26,
//     name: "Amelia Anderson",
//     specializations: ["Drywall", "Plastering"],
//     location: "Atlanta, GA",
//     attributes: {
//       "General Knowledge/Understanding": 87,
//       "Physical Strength": 85,
//       Reliability: 92,
//       Conscientiousness: 89,
//       Stamina: 88,
//       Safety: 93,
//       "Technical Knowledge": 86,
//       Heights: 82,
//       Experience: 90,
//       "Attitude/Social Abilities": 91,
//       "Customer Service": 93,
//       Math: 84,
//       Confidence: 88,
//       Initiative: 87,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 27,
//     name: "Henry Rodriguez",
//     specializations: ["Landscaping", "Lawn Care"],
//     location: "Kansas City, MO",
//     attributes: {
//       "General Knowledge/Understanding": 89,
//       "Physical Strength": 91,
//       Reliability: 90,
//       Conscientiousness: 88,
//       Stamina: 93,
//       Safety: 92,
//       "Technical Knowledge": 87,
//       Heights: 84,
//       Experience: 89,
//       "Attitude/Social Abilities": 92,
//       "Customer Service": 94,
//       Math: 85,
//       Confidence: 90,
//       Initiative: 91,
//       "Work Ethic": 93,
//     },
//   },
//   {
//     id: 28,
//     name: "Evelyn Martin",
//     specializations: ["Tile", "Stone Installation"],
//     location: "Milwaukee, WI",
//     attributes: {
//       "General Knowledge/Understanding": 90,
//       "Physical Strength": 86,
//       Reliability: 93,
//       Conscientiousness: 92,
//       Stamina: 88,
//       Safety: 94,
//       "Technical Knowledge": 91,
//       Heights: 83,
//       Experience: 92,
//       "Attitude/Social Abilities": 89,
//       "Customer Service": 91,
//       Math: 87,
//       Confidence: 90,
//       Initiative: 89,
//       "Work Ethic": 95,
//     },
//   },
//   {
//     id: 29,
//     name: "Alexander White",
//     specializations: ["Carpentry", "Furniture Making"],
//     location: "Las Vegas, NV",
//     attributes: {
//       "General Knowledge/Understanding": 92,
//       "Physical Strength": 89,
//       Reliability: 91,
//       Conscientiousness: 90,
//       Stamina: 88,
//       Safety: 93,
//       "Technical Knowledge": 94,
//       Heights: 85,
//       Experience: 95,
//       "Attitude/Social Abilities": 87,
//       "Customer Service": 89,
//       Math: 91,
//       Confidence: 93,
//       Initiative: 92,
//       "Work Ethic": 94,
//     },
//   },
//   {
//     id: 30,
//     name: "Scarlett Thompson",
//     specializations: ["Interior Design", "Space Planning"],
//     location: "Portland, OR",
//     attributes: {
//       "General Knowledge/Understanding": 95,
//       "Physical Strength": 81,
//       Reliability: 94,
//       Conscientiousness: 96,
//       Stamina: 83,
//       Safety: 92,
//       "Technical Knowledge": 93,
//       Heights: 80,
//       Experience: 91,
//       "Attitude/Social Abilities": 97,
//       "Customer Service": 98,
//       Math: 88,
//       Confidence: 94,
//       Initiative: 95,
//       "Work Ethic": 96,
//     },
//   },
// ];
